/*
Name of Program: EECS 348 Assignment 2 - CEO Email Priority Queue (file names gemini_3.7.c)
Description:     This program prioritizes incoming emails for a busy company CEO
                 using a list-based MaxHeap implementation of a Priority Queue.
                 Emails are prioritized based on the sender category:
                   1. Boss (Highest priority)
                   2. Subordinate
                   3. Peer
                   4. ImportantPerson
                   5. OtherPerson (Lowest priority)
                 If multiple emails have the same sender category, the newest
                 email (by date MM-DD-YYYY) is prioritized first.
                 The program processes commands from an input file:
                   - EMAIL <sender>, <subject>, <date>: Adds email to queue
                   - NEXT: Displays the next email to read without removing it
                   - READ: Marks the highest priority email as read (removes it)
                   - COUNT: Displays count of unread emails
Inputs:          Input file containing commands (via command line argument,
                 prompt, or standard input).
Outputs:         Formatted terminal output for COUNT, NEXT, and empty states. also errors
Collaborators:   None
Other Sources:   Google Gemini (GenAI assistance for EECS 348 Assignment 2)
Author:          Dylan Miller
Creation Date:   September 11, 2026
Revision Date:   September 11, 2026
Revisions:       Created file and had Gemini create first revision of the program
                 commented each line, added new lines between statements to make them more readable
                 Implemented date validation, so now the date must actually exist to be an Email. It will error out if something goes wrong
                 Implemeneted space and time complexity saving things.
                    - MaxHeap array is now an array of pointers to the structs instead of the actual values
                    - The array's memory allocated now shrinks dynamically when emails are removed. Before, it only grew
*/

/*
    All code, unless stated elsewise, was generated by Gemini. I did read all the code, understand the code, and recommend edits to the code, but it was not programmed by my hands unless I say so. I would've loved to write more myself, but we went from hello-world to literally the ladder half of 268 (heaps and stuff). That is kinda bonkers!
*/

// Include standard input/output library for printf, fprintf, fgets, fopen, fclose
#include <stdio.h>

// Include standard utility library for dynamic memory management (malloc, free, realloc) and exit
#include <stdlib.h>

// Include string manipulation library for strcmp, strncpy, strchr, strlen, memset
#include <string.h>

// Include character handling library for isspace
#include <ctype.h>

// Check if compiling on a Windows operating system
#ifdef _WIN32

// Include Windows I/O header for console device checks
#include <io.h>

// Map POSIX isatty to Windows _isatty
#define ISATTY _isatty

// Map POSIX fileno to Windows _fileno
#define FILENO _fileno

// Else branch for non-Windows POSIX systems (Linux, macOS)
#else

// Include standard POSIX system API header for isatty and fileno
#include <unistd.h>

// Use standard POSIX isatty function directly
#define ISATTY isatty

// Use standard POSIX fileno function directly
#define FILENO fileno

// End of platform-specific conditional compilation directive
#endif

// Define maximum allowable character length for sender category string including null terminator
#define MAX_SENDER_LEN   64

// Define maximum allowable character length for subject line string including null terminator
#define MAX_SUBJECT_LEN  256

// Define maximum allowable character length for date string (MM-DD-YYYY) including null terminator
#define MAX_DATE_LEN     16

// Define initial capacity for the dynamic array of the MaxHeap priority queue
#define INITIAL_CAPACITY 64

// Begin definition of structure representing an individual email record
typedef struct {
    // Character array storing the sender category name (e.g., Boss, Peer)
    char sender[MAX_SENDER_LEN];

    // Character array storing the email's subject line
    char subject[MAX_SUBJECT_LEN];

    // Character array storing the original raw date string in MM-DD-YYYY format
    char date[MAX_DATE_LEN];

    // Integer storing the numeric rank priority of sender (Boss=5 down to OtherPerson=1)
    int priority;

    // Normalized integer date representation YYYYMMDD where larger value represents newer date
    int date_val;

    // Monotonically increasing counter recording arrival sequence for FIFO tie-breaking
    int arrival_order;
// Define Email as the type name alias for this struct
} Email;

// Begin definition of structure representing the list-based MaxHeap priority queue
typedef struct {
    // Pointer to dynamic array of pointers to Email records (8 bytes per pointer on 64-bit)
    Email **data;

    // Current count of valid Email items actively stored in the heap
    int size;

    // Current total allocated capacity of pointer slots in the dynamic array
    int capacity;
// Define MaxHeap as the type name alias for this struct
} MaxHeap;

// Declare function prototype for allocating and initializing a new MaxHeap
MaxHeap* create_heap(int initial_capacity);

// Declare function prototype for deallocating a MaxHeap and all its stored elements
void free_heap(MaxHeap *heap);

// Declare function prototype for swapping two Email pointers in the heap array
void swap_emails(Email **a, Email **b);

// Declare function prototype for comparing priority ordering between two Email items
int compare_emails(const Email *a, const Email *b);

// Declare function prototype for restoring heap property by moving an element upward
void heapify_up(MaxHeap *heap, int index);

// Declare function prototype for restoring heap property by moving an element downward
void heapify_down(MaxHeap *heap, int index);

// Declare function prototype for inserting a new Email into the MaxHeap
void insert_email(MaxHeap *heap, Email email);

// Declare function prototype for inspecting the highest-priority Email without removing it
Email* peek_max(MaxHeap *heap);

// Declare function prototype for removing and retrieving the highest-priority Email
int extract_max(MaxHeap *heap, Email *out_email);

// Declare function prototype for mapping a sender category string to numeric rank
int get_sender_priority(const char *sender);

// Declare function prototype for checking if a given year is a leap year
int is_leap_year(int year);

// Declare function prototype for determining the valid number of days in a month and year
int get_days_in_month(int month, int year);

// Declare function prototype for validating a date string according to calendar rules
int is_valid_date(const char *date_str, int *out_date_val);

// Declare function prototype for converting MM-DD-YYYY date string into comparable integer
int parse_date_value(const char *date_str);

// Declare function prototype for stripping leading and trailing whitespace in-place
char* trim_whitespace(char *str);

// Declare function prototype for reading input commands and running queue operations
void process_input(FILE *fp);


// Define function to allocate and initialize a new list-based MaxHeap
MaxHeap* create_heap(int initial_capacity) {
    // Dynamically allocate memory on the heap for the MaxHeap control structure
    MaxHeap *heap = (MaxHeap *)malloc(sizeof(MaxHeap));

    // Verify whether the memory allocation for the heap structure was successful
    if (!heap) {
        // Print memory allocation error message to standard error stream
        fprintf(stderr, "Error: Memory allocation failed for MaxHeap structure.\n");

        // Terminate program execution with failure exit status
        exit(EXIT_FAILURE);
    // End of heap struct allocation check
    }

    // Set initial capacity to given positive argument or fallback to default INITIAL_CAPACITY
    heap->capacity = (initial_capacity > 0) ? initial_capacity : INITIAL_CAPACITY;

    // Initialize heap size to zero since no emails are initially stored
    heap->size = 0;

    // Dynamically allocate memory for pointer array holding heap->capacity Email pointers
    heap->data = (Email **)malloc(sizeof(Email *) * heap->capacity);

    // Verify whether the memory allocation for the dynamic pointer array was successful
    if (!heap->data) {
        // Print memory allocation error message to standard error stream
        fprintf(stderr, "Error: Memory allocation failed for heap data array.\n");

        // Free previously allocated MaxHeap control struct to prevent memory leak
        free(heap);

        // Terminate program execution with failure exit status
        exit(EXIT_FAILURE);
    // End of data array allocation check
    }

    // Return pointer to the newly allocated and initialized MaxHeap structure
    return heap;
// End of function create_heap
}


// Define function to release all dynamically allocated memory of a MaxHeap
void free_heap(MaxHeap *heap) {
    // Check if the heap pointer itself is non-null
    if (heap) {
        // Check if the internal dynamic pointer array is non-null
        if (heap->data) {
            // Loop through each currently stored Email pointer in the heap
            for (int i = 0; i < heap->size; i++) {
                // Check if the individual Email element pointer is non-null
                if (heap->data[i]) {
                    // Deallocate memory for the individual Email struct
                    free(heap->data[i]);
                // End of individual element null check
                }
            // End of loop deallocating elements
            }

            // Deallocate the dynamic array of Email pointers
            free(heap->data);
        // End of heap->data null check
        }

        // Deallocate the MaxHeap control structure itself
        free(heap);
    // End of heap null check
    }
// End of function free_heap
}

// Define helper function to swap two Email pointers in the heap array
void swap_emails(Email **a, Email **b) {
    // Store pointer a into a temporary pointer variable
    Email *temp = *a;

    // Assign pointer b into memory location of pointer a
    *a = *b;

    // Assign saved temporary pointer into memory location of pointer b
    *b = temp;
// End of function swap_emails
}


// Define function to evaluate priority between two emails based on requirements
int compare_emails(const Email *a, const Email *b) {
    // Check if the two emails have different sender category priority ranks
    if (a->priority != b->priority) {
        // Return positive if a has higher sender priority, negative if b has higher
        return a->priority - b->priority;
    // End of priority rank difference check
    }

    // Check if sender priorities match but date values differ (newer date has precedence)
    if (a->date_val != b->date_val) {
        // Return positive if a is newer, negative if b is newer
        return a->date_val - b->date_val;
    // End of date value difference check
    }

    // Both sender rank and date are identical: earlier arrival takes precedence (FIFO)
    return b->arrival_order - a->arrival_order;
// End of function compare_emails
}


// Define function to sift an element up the tree to restore MaxHeap property
void heapify_up(MaxHeap *heap, int index) {
    // Continue moving upward as long as the current node is not the root
    while (index > 0) {
        // Calculate the parent node index using zero-based array formula (index - 1) / 2
        int parent = (index - 1) / 2;

        // Compare child element with parent; check if child has higher priority
        if (compare_emails(heap->data[index], heap->data[parent]) > 0) {
            // Swap child pointer with parent pointer (fast 8-byte pointer swap)
            swap_emails(&heap->data[index], &heap->data[parent]);

            // Update current index to parent position to continue checking upwards
            index = parent;
        // Child priority is less than or equal to parent: heap property satisfied
        } else {
            // Exit loop early as element is now in valid heap position
            break;
        // End of else branch
        }
    // End of while loop for heapify_up
    }
// End of function heapify_up
}


// Define function to sink an element down the tree to restore MaxHeap property
void heapify_down(MaxHeap *heap, int index) {
    // Loop continuously until the element reaches its correct position or becomes a leaf
    while (1) {
        // Calculate the zero-based array index of left child node (2 * index + 1)
        int left = 2 * index + 1;

        // Calculate the zero-based array index of right child node (2 * index + 2)
        int right = 2 * index + 2;

        // Initialize largest index tracker to the current parent node index
        int largest = index;

        // Check if left child exists and has higher priority than current largest
        if (left < heap->size && compare_emails(heap->data[left], heap->data[largest]) > 0) {
            // Record left child as the current highest priority candidate
            largest = left;
        // End of left child comparison check
        }

        // Check if right child exists and has higher priority than current largest
        if (right < heap->size && compare_emails(heap->data[right], heap->data[largest]) > 0) {
            // Record right child as the highest priority candidate
            largest = right;
        // End of right child comparison check
        }

        // Check if either child has higher priority than the parent at index
        if (largest != index) {
            // Swap current pointer with child pointer (fast 8-byte pointer swap)
            swap_emails(&heap->data[index], &heap->data[largest]);

            // Advance index to the swapped child position to continue sifting downward
            index = largest;
        // Current element is larger than or equal to both children: heap invariant holds
        } else {
            // Exit the loop as element is in its valid heap position
            break;
        // End of else branch
        }
    // End of while loop for heapify_down
    }
// End of function heapify_down
}


// Define function to insert a new email into the priority queue
void insert_email(MaxHeap *heap, Email email) {
    // Check if the current number of emails has reached or exceeded allocated capacity
    if (heap->size >= heap->capacity) {
        // Double the allocated pointer capacity value
        heap->capacity *= 2;

        // Reallocate the dynamic pointer array to the new doubled capacity
        Email **new_data = (Email **)realloc(heap->data, sizeof(Email *) * heap->capacity);

        // Check if memory reallocation failed
        if (!new_data) {
            // Print error message to stderr indicating failure during heap buffer expansion
            fprintf(stderr, "Error: Memory reallocation failed during heap expansion.\n");

            // Terminate program execution with failure exit status
            exit(EXIT_FAILURE);
        // End of reallocation failure check
        }

        // Update heap data pointer to the newly resized pointer buffer
        heap->data = new_data;
    // End of capacity expansion check
    }

    // Allocate memory on the heap for the new individual Email record
    Email *new_item = (Email *)malloc(sizeof(Email));

    // Verify whether the memory allocation for the Email struct succeeded
    if (!new_item) {
        // Print memory allocation error message to standard error stream
        fprintf(stderr, "Error: Memory allocation failed for email item.\n");

        // Terminate program execution with failure exit status
        exit(EXIT_FAILURE);
    // End of email item allocation check
    }

    // Copy the contents of the given email into the newly allocated heap memory
    *new_item = email;

    // Determine array index for new email pointer at next available leaf position
    int current_index = heap->size;

    // Store pointer to new email at end of the heap pointer array
    heap->data[current_index] = new_item;

    // Increment the count of stored emails in the heap
    heap->size++;

    // Restore the heap invariant by bubbling the newly added email upward
    heapify_up(heap, current_index);
// End of function insert_email
}


// Define function to view the root (highest priority) email without removing it
Email* peek_max(MaxHeap *heap) {
    // Check if the priority queue contains zero emails
    if (heap->size == 0) {
        // Return NULL pointer indicating queue is currently empty
        return NULL;
    // End of empty queue check
    }

    // Return pointer to root element at index 0 which holds highest priority
    return heap->data[0];
// End of function peek_max
}


// Define function to remove and return the highest priority email from the queue
int extract_max(MaxHeap *heap, Email *out_email) {
    // Check if the heap has no elements to remove
    if (heap->size == 0) {
        // Return 0 indicating removal failure due to empty queue
        return 0;
    // End of empty queue check
    }

    // Check if caller provided an output pointer to receive extracted email contents
    if (out_email) {
        // Copy root email contents into destination struct pointed to by out_email
        *out_email = *heap->data[0];
    // End of out_email check
    }

    // Free dynamically allocated memory of root Email struct being extracted
    free(heap->data[0]);

    // Move the last element pointer in the heap into the root position
    heap->data[0] = heap->data[heap->size - 1];

    // Decrement the total count of emails in the heap
    heap->size--;

    // Check if elements still remain in the heap after removal
    if (heap->size > 0) {
        // Restore heap property by sinking new root element downward to its valid position
        heapify_down(heap, 0);
    // End of non-empty heap check
    }

    // Check if heap usage dropped below one quarter capacity to shrink array and conserve RAM
    if (heap->size > 0 && heap->size <= heap->capacity / 4 && heap->capacity > INITIAL_CAPACITY) {
        // Halve the current allocated pointer capacity
        heap->capacity /= 2;

        // Reallocate pointer array to smaller capacity
        Email **shrunk_data = (Email **)realloc(heap->data, sizeof(Email *) * heap->capacity);

        // Verify that realloc returned a valid memory address
        if (shrunk_data) {
            // Update heap data pointer to the newly compacted array
            heap->data = shrunk_data;
        // End of shrunk_data check
        }
    // End of dynamic heap shrink check
    }

    // Return 1 indicating successful removal of highest-priority email
    return 1;
// End of function extract_max
}


// Define function to map a sender category string to integer priority rank
int get_sender_priority(const char *sender) {
    // Check if sender category matches "Boss" exactly
    if (strcmp(sender, "Boss") == 0) {
        // Return highest priority rank 5
        return 5;
    // End of Boss check
    }

    // Check if sender category matches "Subordinate" exactly
    if (strcmp(sender, "Subordinate") == 0) {
        // Return priority rank 4
        return 4;
    // End of Subordinate check
    }

    // Check if sender category matches "Peer" exactly
    if (strcmp(sender, "Peer") == 0) {
        // Return priority rank 3
        return 3;
    // End of Peer check
    }

    // Check if sender category matches "ImportantPerson" exactly
    if (strcmp(sender, "ImportantPerson") == 0) {
        // Return priority rank 2
        return 2;
    // End of ImportantPerson check
    }

    // Check if sender category matches "OtherPerson" exactly
    if (strcmp(sender, "OtherPerson") == 0) {
        // Return lowest priority rank 1
        return 1;
    // End of OtherPerson check
    }

    // Return fallback priority 0 for any unrecognized sender category string
    return 0;
// End of function get_sender_priority
}


// Define helper function to check whether a given year is a leap year
int is_leap_year(int year) {
    // Return true if divisible by 4 and not 100, or if divisible by 400
    return ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0));
// End of function is_leap_year
}


// Define helper function to return the valid number of days in a given month and year
int get_days_in_month(int month, int year) {
    // Check if month is outside valid range of 1 through 12
    if (month < 1 || month > 12) {
        // Return 0 indicating an invalid month
        return 0;
    // End of month range check
    }

    // Check if month is February
    if (month == 2) {
        // Return 29 if leap year, otherwise return 28
        return is_leap_year(year) ? 29 : 28;
    // End of February check
    }

    // Check if month has 30 days (April, June, September, November)
    if (month == 4 || month == 6 || month == 9 || month == 11) {
        // Return 30 days
        return 30;
    // End of 30-day month check
    }

    // Return 31 days for all remaining months (Jan, Mar, May, Jul, Aug, Oct, Dec)
    return 31;
// End of function get_days_in_month
}


// Define function to validate date string against calendar rules and compute integer value
int is_valid_date(const char *date_str, int *out_date_val) {
    // Check if date string pointer is NULL
    if (!date_str) {
        // Return 0 indicating invalid date
        return 0;
    // End of NULL check
    }

    // Declare integer variables to store parsed month, day, and year components
    int month = 0, day = 0, year = 0;

    // Declare character variable to check for unexpected trailing characters
    char trailing = '\0';

    // Parse month, day, and year ensuring no trailing characters exist
    if (sscanf(date_str, "%d-%d-%d %c", &month, &day, &year, &trailing) != 3) {
        // Return 0 indicating format did not match expected MM-DD-YYYY pattern
        return 0;
    // End of sscanf matching check
    }

    // Check if month is outside valid calendar range of 1 to 12
    if (month < 1 || month > 12) {
        // Return 0 indicating invalid month value
        return 0;
    // End of month validity check
    }

    // Check if year is non-positive
    if (year <= 0) {
        // Return 0 indicating invalid year value
        return 0;
    // End of year validity check
    }

    // Retrieve maximum allowable days for the given month and year
    int max_days = get_days_in_month(month, year);

    // Check if day is less than 1 or exceeds maximum allowed days for the month
    if (day < 1 || day > max_days) {
        // Return 0 indicating day is outside valid calendar range
        return 0;
    // End of day validity check
    }

    // Check if caller supplied pointer to receive calculated date value
    if (out_date_val) {
        // Compute and store composite integer formatted as YYYYMMDD
        *out_date_val = (year * 10000) + (month * 100) + day;
    // End of out_date_val check
    }

    // Return 1 indicating date is valid
    return 1;
// End of function is_valid_date
}

// Define function to parse MM-DD-YYYY date string into an integer YYYYMMDD
int parse_date_value(const char *date_str) {
    // Declare integer variable to hold parsed date value
    int date_val = 0;

    // Validate and parse the date string
    if (is_valid_date(date_str, &date_val)) {
        // Return the valid parsed date value
        return date_val;
    // End of validity check
    }

    // Return 0 if date format is invalid or unparseable
    return 0;
// End of function parse_date_value
}


// Define helper function to remove leading and trailing whitespace in-place
char* trim_whitespace(char *str) {
    // Check if the input string pointer is NULL
    if (!str) {
        // Return NULL pointer indicating invalid input string
        return NULL;
    // End of NULL check
    }

    // Advance pointer while current character is any whitespace character
    while (isspace((unsigned char)*str)) {
        // Increment string pointer past whitespace character
        str++;
    // End of leading whitespace trimming loop
    }

    // Check if string consists solely of whitespace and reached null terminator
    if (*str == '\0') {
        // Return pointer to empty string
        return str;
    // End of empty string check
    }

    // Calculate pointer to the last non-null character in the string
    char *end = str + strlen(str) - 1;

    // Backtrack from end while current character is a whitespace character
    while (end > str && isspace((unsigned char)*end)) {
        // Overwrite trailing whitespace character with null terminator
        *end = '\0';

        // Move pointer backward toward beginning of string
        end--;
    // End of trailing whitespace trimming loop
    }

    // Return pointer to first non-whitespace character in the trimmed string
    return str;
// End of function trim_whitespace
}

// Define function to read and process commands from the open file stream
void process_input(FILE *fp) {
    // Create a new priority queue heap initialized with default capacity
    MaxHeap *heap = create_heap(INITIAL_CAPACITY);

    // Allocate stack buffer of 1024 bytes to hold each line read from input file
    char line[1024];

    // Initialize monotonic insertion counter for preserving arrival order
    int global_order = 0;

    // Read input file line by line until EOF (fgets returns NULL)
    while (fgets(line, sizeof(line), fp) != NULL) {
        // Strip trailing carriage return and newline characters in-place
        line[strcspn(line, "\r\n")] = '\0';

        // Trim leading and trailing whitespace from the line buffer
        char *trimmed_line = trim_whitespace(line);

        // Check if trimmed line is completely empty
        if (strlen(trimmed_line) == 0) {
            // Skip processing for blank lines and continue to next line
            continue;
        // End of blank line check
        }

        // Check if line begins with command "EMAIL" followed by whitespace delimiter
        if (strncmp(trimmed_line, "EMAIL", 5) == 0 && (trimmed_line[5] == ' ' || trimmed_line[5] == '\t')) {
            // Set pointer past the "EMAIL" command keyword
            char *content = trimmed_line + 5;

            // Advance pointer to skip spaces or tabs preceding first argument
            while (*content == ' ' || *content == '\t') content++;

            // Locate the first comma delimiter separating sender from subject
            char *comma1 = strchr(content, ',');

            // Validate that first comma delimiter exists; if missing, skip malformed line
            if (!comma1) {
                // Skip processing malformed line and proceed to next command
                continue;
            // End of comma1 validation check
            }

            // Replace first comma with null terminator to isolate sender substring
            *comma1 = '\0';

            // Trim whitespace from sender string component
            char *sender_part = trim_whitespace(content);

            // Set pointer to beginning of subject text immediately following first comma
            char *after_comma1 = comma1 + 1;

            // Locate second comma delimiter separating subject from date
            char *comma2 = strchr(after_comma1, ',');

            // Validate that second comma delimiter exists; if missing, skip malformed line
            if (!comma2) {
                // Skip processing malformed line and proceed to next command
                continue;
            // End of comma2 validation check
            }

            // Replace second comma with null terminator to isolate subject substring
            *comma2 = '\0';

            // Trim whitespace from subject string component
            char *subject_part = trim_whitespace(after_comma1);

            // Trim whitespace from date string component following second comma
            char *date_part = trim_whitespace(comma2 + 1);

            // Declare integer variable to store validated date value
            int date_val = 0;

            // Validate date string according to calendar rules and valid month/day ranges
            if (!is_valid_date(date_part, &date_val)) {
                // Print error message to standard error stream indicating invalid date
                fprintf(stderr, "Error: Invalid date '%s' in EMAIL command.\n", date_part);

                // Skip processing this email and proceed to next command line
                continue;
            // End of date validation check
            }

            // Declare Email struct variable to assemble the new record
            Email new_email;

            // Zero out entire memory of Email structure for clean initialization
            memset(&new_email, 0, sizeof(Email));

            // Safely copy sender string into new_email struct buffer with bound check
            strncpy(new_email.sender, sender_part, sizeof(new_email.sender) - 1);

            // Safely copy subject line into new_email struct buffer with bound check
            strncpy(new_email.subject, subject_part, sizeof(new_email.subject) - 1);

            // Safely copy date string into new_email struct buffer with bound check
            strncpy(new_email.date, date_part, sizeof(new_email.date) - 1);

            // Compute and assign numeric priority rank from sender string
            new_email.priority = get_sender_priority(new_email.sender);

            // Store the validated numerical date value YYYYMMDD
            new_email.date_val = date_val;

            // Increment arrival counter and store order ID for FIFO tie-breaker
            new_email.arrival_order = ++global_order;

            // Insert newly constructed email record into the priority queue
            insert_email(heap, new_email);
        // Check if command keyword is "COUNT"
        } else if (strcmp(trimmed_line, "COUNT") == 0) {
            // Print the current count of unread emails residing in the heap
            printf("There are %d emails to read.\n", heap->size);
        // Check if command keyword is "NEXT"
        } else if (strcmp(trimmed_line, "NEXT") == 0) {
            // Retrieve pointer to highest-priority email without popping it
            Email *next = peek_max(heap);

            // Check if queue currently contains at least one email
            if (next != NULL) {
                // Print header banner for next email
                printf("Next email:\n");

                // Print sender of the highest-priority email indented with 4 spaces
                printf("    Sender: %s\n", next->sender);

                // Print subject line of highest-priority email indented with 4 spaces
                printf("    Subject: %s\n", next->subject);

                // Print date string of highest-priority email indented with 4 spaces
                printf("    Date: %s\n", next->date);
            // Else branch executed when priority queue is empty
            } else {
                // Print notice indicating there are no emails available to read
                printf("No emails to read.\n");
            // End of non-empty next email check
            }
        // Check if command keyword is "READ"
        } else if (strcmp(trimmed_line, "READ") == 0) {
            // Remove highest-priority email from queue without storing or printing output
            extract_max(heap, NULL);
        // End of command dispatch ladder
        }
    // End of while loop reading file line by line
    }

    // Free all dynamically allocated memory used by the heap before returning
    free_heap(heap);
// End of function process_input
}


// Define program entry point main function
int main(int argc, char *argv[]) {
    // Initialize file pointer to NULL
    FILE *fp = NULL;

    // Check if user provided command-line arguments (argc > 1 implies filename passed)
    if (argc > 1) {
        // Open the file passed as first command-line argument for reading
        fp = fopen(argv[1], "r");

        // Check if file could not be opened
        if (!fp) {
            // Print error message with filename to standard error stream
            fprintf(stderr, "Error: Could not open file '%s'\n", argv[1]);

            // Terminate program with failure code
            return EXIT_FAILURE;
        // End of file open error check
        }
    // Branch executed when no command-line argument was supplied
    } else {
        // Check if standard input is redirected from a pipe or file (non-terminal)
        if (!ISATTY(FILENO(stdin))) {
            // Use standard input stream directly as the input source
            fp = stdin;
        // Branch executed when running interactively from terminal prompt
        } else {
            // Declare stack buffer of 256 bytes to hold user-entered filename
            char filename[256];

            // Display interactive prompt asking user for filename
            printf("Enter input file name: ");

            // Read filename input from terminal standard input
            if (fgets(filename, sizeof(filename), stdin) != NULL) {
                // Strip trailing newline characters from user-entered filename
                filename[strcspn(filename, "\r\n")] = '\0';

                // Trim leading and trailing whitespace from the entered filename
                char *clean_name = trim_whitespace(filename);

                // Check if user entered a non-empty filename string
                if (strlen(clean_name) > 0) {
                    // Attempt to open specified file for reading
                    fp = fopen(clean_name, "r");

                    // Check if specified file could not be opened
                    if (!fp) {
                        // Print file open error message to stderr
                        fprintf(stderr, "Error: Could not open file '%s'\n", clean_name);

                        // Return failure exit code
                        return EXIT_FAILURE;
                    // End of interactive file open error check
                    }
                // User pressed enter without typing a filename
                } else {
                    // Fall back to reading from standard input
                    fp = stdin;
                // End of clean_name length check
                }
            // Error or EOF encountered while reading user input prompt
            } else {
                // Return success exit code immediately
                return EXIT_SUCCESS;
            // End of interactive fgets check
            }
        // End of interactive terminal branch
        }
    // End of argument count check
    }

    // Process all email priority queue commands from the opened file stream
    process_input(fp);

    // Check if input stream was a regular file (not stdin) and validly open
    if (fp != stdin && fp != NULL) {
        // Close the opened file stream
        fclose(fp);
    // End of file closure check
    }

    // Return program success exit code 0 to operating system
    return EXIT_SUCCESS;
// End of function main
}
